version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/maxence-charriere/murlok
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -race .
      - run: go test -v -race ./internal/...
      - run: go test -v -race ./cmd/murlok
