// Code generated by go generate; DO NOT EDIT.
package core

const bridgeJS = `const murlok = {
    url: '{{.LocalServerURL}}',
    rpcURL: '{{.LocalServerURL}}/murlok',
    onEvent: function (name = '', arg = {}) {
        console.log('murlok event not handled => ' + name + ': ' + JSON.stringify(arg));
    },
};`
